name: Auto Author Assign

on:
  pull_request_target:
    types: [ opened, reopened ]

permissions:
  pull-requests: write

jobs:
  assign-author:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: toshimaru/auto-author-assign@v1.6.2
