on: push
name: CI
jobs:
  lint:
    name: Lint
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Install Poetry
        run: python -m pip install --upgrade poetry==1.5.1
      - name: Config poetry
        run: poetry config virtualenvs.create false
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi --no-cache
      - name: Lint
        run: ruff .
  type_checking:
    name: Static type checking
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install Poetry
        run: python -m pip install --upgrade poetry==1.5.1
      - name: Config poetry
        run: poetry config virtualenvs.create false
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi --no-cache
      - name: Lint
        run: mypy .
  tests:
    name: Unit-tests
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install Poetry
        run: python -m pip install --upgrade poetry==1.5.1
      - name: Config poetry
        run: poetry config virtualenvs.create false
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi --no-cache
      - name: Pytest
        run: pytest .
